[project]
name = "atlas-ftag-tools"
version = "0.1"
description = "ATLAS Flavour Tagging Tools"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
  "h5py",
  "numpy",
]

[project.optional-dependencies]
dev = [
  "black==23.1.0",
  "darglint==1.8.1",
  "ruff==0.0.254",
  "pytest==7.2.2",
  "pytest-cov==4.0.0",
  "pytest_notebook==0.8.1",
  "ipykernel==6.21.3",
]

[tool.setuptools]
packages = ["ftag"]

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
preview = "True"

[tool.darglint]
ignore = ["DAR203", "DAR103"]
docstring_style = "numpy"
strictness = "full"
log_level = "INFO"

[tool.ruff]
select = ["I", "E", "W", "F", "B", "UP", "ARG", "SIM", "TID", "RUF", "D2", "D3", "D4"]
ignore = ["D211", "D213", "RUF005"]
line-length = 100

[tool.pytest]
nb_exec_timeout = 50
nb_coverage = "True"

[mypy]
ignore_missing_imports = "True"
