name: Linting
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
jobs:
  linter:
    runs-on: ubuntu-latest
    container: python:3.11.2-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: python -m pip install -e .[dev] # install in editable mode with additional development tools
      - run: ruff check ftag/
  darglint:
    runs-on: ubuntu-latest
    container: python:3.11.2-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install darglint
        run: pip install darglint==1.8.1
      - run: darglint .
  black:
    runs-on: ubuntu-latest
    container: python:3.11.2-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install black
        run: pip install black==22.3.0
      - run: black --check .
